/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Metadata {
    definitionBuild: string;
    description: string;
}
export interface Build {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    items: Array<Item>;
}
export type Time = bigint;
export interface Item {
    id: bigint;
    cost?: number;
    name: string;
    notes?: string;
    quantity: bigint;
}
export interface BuildData {
    name: string;
    description: string;
}
export interface UserProfile {
    name: string;
}
export enum SortDirection {
    asc = "asc",
    desc = "desc"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addItem(buildId: bigint, item: Item): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBuild(data: BuildData): Promise<bigint>;
    deleteBuild(buildId: bigint): Promise<void>;
    getBuild(buildId: bigint): Promise<Build | null>;
    getBuilds(): Promise<Array<Build>>;
    getBuildsSortedByCreatedAt(direction: SortDirection): Promise<Array<Build>>;
    getBuildsSortedByName(direction: SortDirection): Promise<Array<Build>>;
    getBuildsSortedByUpdatedAt(direction: SortDirection): Promise<Array<Build>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getItems(buildId: bigint): Promise<Array<Item> | null>;
    getItemsSortedByQuantity(buildId: bigint, direction: SortDirection): Promise<Array<Item> | null>;
    getMetadata(): Promise<Metadata | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeItem(buildId: bigint, itemId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setMetadata(metadata: Metadata): Promise<void>;
    updateBuild(buildId: bigint, data: BuildData, clearItems: boolean): Promise<void>;
    updateItem(buildId: bigint, itemId: bigint, updatedItem: Item): Promise<void>;
}
import type { Build as _Build, Item as _Item, Metadata as _Metadata, SortDirection as _SortDirection, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addItem(arg0: bigint, arg1: Item): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, to_candid_Item_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, to_candid_Item_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBuild(arg0: BuildData): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuild(arg0);
            return result;
        }
    }
    async deleteBuild(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBuild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBuild(arg0);
            return result;
        }
    }
    async getBuild(arg0: bigint): Promise<Build | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuild(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuild(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuilds(): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuilds();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuilds();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildsSortedByCreatedAt(arg0: SortDirection): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildsSortedByCreatedAt(to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildsSortedByCreatedAt(to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildsSortedByName(arg0: SortDirection): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildsSortedByName(to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildsSortedByName(to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildsSortedByUpdatedAt(arg0: SortDirection): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildsSortedByUpdatedAt(to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildsSortedByUpdatedAt(to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItems(arg0: bigint): Promise<Array<Item> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItems(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItems(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsSortedByQuantity(arg0: bigint, arg1: SortDirection): Promise<Array<Item> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsSortedByQuantity(arg0, to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsSortedByQuantity(arg0, to_candid_SortDirection_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetadata(): Promise<Metadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetadata();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetadata();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeItem(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeItem(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setMetadata(arg0: Metadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMetadata(arg0);
            return result;
        }
    }
    async updateBuild(arg0: bigint, arg1: BuildData, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBuild(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBuild(arg0, arg1, arg2);
            return result;
        }
    }
    async updateItem(arg0: bigint, arg1: bigint, arg2: Item): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1, to_candid_Item_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1, to_candid_Item_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Build_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Build): Build {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Item>]): Array<Item> | null {
    return value.length === 0 ? null : from_candid_vec_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Metadata]): Metadata | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Build]): Build | null {
    return value.length === 0 ? null : from_candid_Build_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cost: [] | [number];
    name: string;
    notes: [] | [string];
    quantity: bigint;
}): {
    id: bigint;
    cost?: number;
    name: string;
    notes?: string;
    quantity: bigint;
} {
    return {
        id: value.id,
        cost: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.cost)),
        name: value.name,
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    items: Array<_Item>;
}): {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    items: Array<Item>;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        items: from_candid_vec_n8(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Build>): Array<Build> {
    return value.map((x)=>from_candid_Build_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Item_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Item): _Item {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SortDirection_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortDirection): _SortDirection {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cost?: number;
    name: string;
    notes?: string;
    quantity: bigint;
}): {
    id: bigint;
    cost: [] | [number];
    name: string;
    notes: [] | [string];
    quantity: bigint;
} {
    return {
        id: value.id,
        cost: value.cost ? candid_some(value.cost) : candid_none(),
        name: value.name,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortDirection): {
    asc: null;
} | {
    desc: null;
} {
    return value == SortDirection.asc ? {
        asc: null
    } : value == SortDirection.desc ? {
        desc: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
