/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Build {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'items' : Array<Item>,
}
export interface BuildData { 'name' : string, 'description' : string }
export interface Item {
  'id' : bigint,
  'cost' : [] | [number],
  'name' : string,
  'notes' : [] | [string],
  'quantity' : bigint,
}
export interface Metadata { 'definitionBuild' : string, 'description' : string }
export type SortDirection = { 'asc' : null } |
  { 'desc' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItem' : ActorMethod<[bigint, Item], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBuild' : ActorMethod<[BuildData], bigint>,
  'deleteBuild' : ActorMethod<[bigint], undefined>,
  'getBuild' : ActorMethod<[bigint], [] | [Build]>,
  'getBuilds' : ActorMethod<[], Array<Build>>,
  'getBuildsSortedByCreatedAt' : ActorMethod<[SortDirection], Array<Build>>,
  'getBuildsSortedByName' : ActorMethod<[SortDirection], Array<Build>>,
  'getBuildsSortedByUpdatedAt' : ActorMethod<[SortDirection], Array<Build>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItems' : ActorMethod<[bigint], [] | [Array<Item>]>,
  'getItemsSortedByQuantity' : ActorMethod<
    [bigint, SortDirection],
    [] | [Array<Item>]
  >,
  'getMetadata' : ActorMethod<[], [] | [Metadata]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeItem' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMetadata' : ActorMethod<[Metadata], undefined>,
  'updateBuild' : ActorMethod<[bigint, BuildData, boolean], undefined>,
  'updateItem' : ActorMethod<[bigint, bigint, Item], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];