/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({
  'id' : IDL.Nat,
  'cost' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BuildData = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Build = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'items' : IDL.Vec(Item),
});
export const SortDirection = IDL.Variant({
  'asc' : IDL.Null,
  'desc' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Metadata = IDL.Record({
  'definitionBuild' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItem' : IDL.Func([IDL.Nat, Item], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBuild' : IDL.Func([BuildData], [IDL.Nat], []),
  'deleteBuild' : IDL.Func([IDL.Nat], [], []),
  'getBuild' : IDL.Func([IDL.Nat], [IDL.Opt(Build)], ['query']),
  'getBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
  'getBuildsSortedByCreatedAt' : IDL.Func(
      [SortDirection],
      [IDL.Vec(Build)],
      ['query'],
    ),
  'getBuildsSortedByName' : IDL.Func(
      [SortDirection],
      [IDL.Vec(Build)],
      ['query'],
    ),
  'getBuildsSortedByUpdatedAt' : IDL.Func(
      [SortDirection],
      [IDL.Vec(Build)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItems' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(Item))], ['query']),
  'getItemsSortedByQuantity' : IDL.Func(
      [IDL.Nat, SortDirection],
      [IDL.Opt(IDL.Vec(Item))],
      ['query'],
    ),
  'getMetadata' : IDL.Func([], [IDL.Opt(Metadata)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMetadata' : IDL.Func([Metadata], [], []),
  'updateBuild' : IDL.Func([IDL.Nat, BuildData, IDL.Bool], [], []),
  'updateItem' : IDL.Func([IDL.Nat, IDL.Nat, Item], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'cost' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BuildData = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Time = IDL.Int;
  const Build = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'items' : IDL.Vec(Item),
  });
  const SortDirection = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Metadata = IDL.Record({
    'definitionBuild' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItem' : IDL.Func([IDL.Nat, Item], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBuild' : IDL.Func([BuildData], [IDL.Nat], []),
    'deleteBuild' : IDL.Func([IDL.Nat], [], []),
    'getBuild' : IDL.Func([IDL.Nat], [IDL.Opt(Build)], ['query']),
    'getBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
    'getBuildsSortedByCreatedAt' : IDL.Func(
        [SortDirection],
        [IDL.Vec(Build)],
        ['query'],
      ),
    'getBuildsSortedByName' : IDL.Func(
        [SortDirection],
        [IDL.Vec(Build)],
        ['query'],
      ),
    'getBuildsSortedByUpdatedAt' : IDL.Func(
        [SortDirection],
        [IDL.Vec(Build)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItems' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(Item))], ['query']),
    'getItemsSortedByQuantity' : IDL.Func(
        [IDL.Nat, SortDirection],
        [IDL.Opt(IDL.Vec(Item))],
        ['query'],
      ),
    'getMetadata' : IDL.Func([], [IDL.Opt(Metadata)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMetadata' : IDL.Func([Metadata], [], []),
    'updateBuild' : IDL.Func([IDL.Nat, BuildData, IDL.Bool], [], []),
    'updateItem' : IDL.Func([IDL.Nat, IDL.Nat, Item], [], []),
  });
};

export const init = ({ IDL }) => { return []; };